"""Multi-split robustness sweep: 3 splits x 8 seeds x {ResNet-50, ViT-B/16}.

Each split is one of splits_alt{0,1,2}.parquet, generated by
27_multisplit_gen.py. For every split, we train 8 seeds of ResNet-50 and
8 seeds of ViT-B/16, varying only the master seed; hyperparameters are
inherited from polygeo.train defaults to match the Exp 1 main sweep.

Runs are restartable: any run whose predictions and summary files exist is
skipped. Predictions are saved to
predictions/multisplit_split{k}_{arch}_seed{j}_test_preds.npz. Checkpoints are
not retained because the robustness analysis uses the test predictions.
"""
from __future__ import annotations
import json
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "src"))

import polygeo.data as polygeo_data
import polygeo.paths as polygeo_paths
from polygeo.train import TrainConfig, run_one, get_arch_defaults
from polygeo.paths import RUNS, PREDICTIONS, ROOT, DATA


SPLIT_FILES = [
    DATA / "splits_alt0.parquet",
    DATA / "splits_alt1.parquet",
    DATA / "splits_alt2.parquet",
]
ARCHS = [
    ("resnet50", "imagenet21k", 8),
    ("vit_b16", "imagenet21k", 8),
]
DEVICE = "cuda:0"


def _patch_splits_path(p: Path) -> None:
    """Override the SPLITS path referenced inside polygeo.data and polygeo.paths."""
    polygeo_data.SPLITS = p
    polygeo_paths.SPLITS = p


def main() -> None:
    PREDICTIONS.mkdir(parents=True, exist_ok=True)
    t_total = time.time()
    n_done = n_skipped = n_failed = 0
    log: list[dict] = []

    for split_idx, split_path in enumerate(SPLIT_FILES):
        assert split_path.exists(), f"missing split file: {split_path}"
        _patch_splits_path(split_path)
        print(f"\n=========================================")
        print(f"  SPLIT {split_idx}  ({split_path.name})")
        print(f"=========================================")

        for arch, init, n_seeds in ARCHS:
            defaults = get_arch_defaults(arch, init)
            for seed in range(n_seeds):
                run_name = f"multisplit_split{split_idx}_{arch}_seed{seed:03d}"
                pred_path = PREDICTIONS / f"{run_name}_test_preds.npz"
                summary_path = RUNS / run_name / "summary.json"
                if pred_path.exists() and summary_path.exists():
                    n_skipped += 1
                    continue

                cfg = TrainConfig(
                    arch=arch,
                    init=init,
                    seed=seed,
                    epochs=defaults["epochs"],
                    batch_size=defaults["batch_size"],
                    lr=defaults["lr"],
                    weight_decay=defaults.get("weight_decay", 0.05),
                    run_name=run_name,
                    save_checkpoint=False,
                    save_predictions=True,
                    device=DEVICE,
                )
                t0 = time.time()
                print(f"\n>>> {run_name}  (split={split_idx} arch={arch} seed={seed})")
                try:
                    summ = run_one(cfg)
                    summ["split_idx"] = split_idx
                    summ["split_file"] = str(split_path.name)
                    summ["run_name"] = run_name
                    log.append({
                        "run_name": run_name,
                        "split_idx": split_idx,
                        "arch": arch,
                        "seed": seed,
                        "test_rmse_mean": summ["test_rmse_mean"],
                        "elapsed_h": summ["elapsed_h"],
                    })
                    (RUNS / run_name / "summary.json").write_text(json.dumps(summ, indent=2))
                    n_done += 1
                    elapsed = (time.time() - t0) / 60
                    print(f">>> done in {elapsed:.1f} min  (rmse={summ['test_rmse_mean']:.4f})")
                except Exception as e:
                    print(f">>> FAILED: {e!r}")
                    (RUNS / run_name).mkdir(parents=True, exist_ok=True)
                    (RUNS / run_name / "FAILED.txt").write_text(repr(e))
                    n_failed += 1

    total_h = (time.time() - t_total) / 3600
    out = {
        "n_done": n_done,
        "n_skipped": n_skipped,
        "n_failed": n_failed,
        "total_wallclock_h": total_h,
        "log": log,
    }
    out_path = DATA / "multisplit_sweep_summary.json"
    out_path.write_text(json.dumps(out, indent=2))
    print(f"\n=========================================")
    print(f"  DONE: {n_done} new, {n_skipped} skipped, {n_failed} failed")
    print(f"  total wallclock: {total_h:.2f} h")
    print(f"  summary: {out_path}")


if __name__ == "__main__":
    main()
